name             'apache_tomcat'
maintainer       'Drew A. Blessing'
maintainer_email 'cookbooks@blessing.io'
license          'Apache 2.0'
description      'Installs/Configures tomcat'
long_description 'Installs/Configures tomcat'
version          '0.3.0'

depends 'poise', '~> 2.0'
depends 'ark', '~> 0.9'
depends 'java', '~> 1.31'
depends 'runit', '~> 1.7'
