name             'tomcat'
maintainer       'Drew A. Blessing'
maintainer_email 'cookbooks@blessing.io'
license          'all_rights'
description      'Installs/Configures tomcat'
long_description 'Installs/Configures tomcat'
version          '0.1.0'

depends 'poise', '~> 2.0'
depends 'ark', '~> 0.9'
